'use client';

export default function TermsPage() {
  return (
    <>
      <style jsx global>{`
        .terms-page {
          max-width: 720px;
          margin: 0 auto;
          padding: 3rem 1.5rem;
          line-height: 1.7;
        }
        .terms-page h1 {
          font-size: 2rem;
          font-weight: 700;
          color: rgba(255,255,255,0.95);
          margin-bottom: 0.5rem;
        }
        .terms-page .updated {
          font-size: 0.85rem;
          color: rgba(255,255,255,0.3);
          margin-bottom: 2.5rem;
        }
        .terms-page h2 {
          font-size: 1.2rem;
          font-weight: 600;
          color: rgba(255,255,255,0.9);
          margin-top: 2rem;
          margin-bottom: 0.75rem;
        }
        .terms-page p,
        .terms-page li {
          font-size: 0.95rem;
          color: rgba(255,255,255,0.65);
          margin-bottom: 0.75rem;
        }
        .terms-page ul {
          padding-left: 1.5rem;
          margin-bottom: 0.75rem;
        }
        .terms-page a {
          color: #00D4FF;
          text-decoration: none;
        }
        .terms-page a:hover {
          text-decoration: underline;
        }
        .terms-page .back {
          display: inline-block;
          margin-top: 3rem;
          font-size: 0.85rem;
          color: #00E5A0;
        }
      `}</style>

      <div className="terms-page">
        <h1>Terms of Service</h1>
        <p className="updated">Last updated: April 3, 2026</p>

        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your use of mobile applications
          published by SkoobiLabs (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;),
          including HearZ, HearVerse, and any other SkoobiLabs apps. By using our apps, you
          agree to these Terms.
        </p>

        <h2>Use of Our Apps</h2>
        <p>
          Our apps provide audio content through AI text-to-speech technology. You may use our
          apps for personal, non-commercial purposes. You agree not to:
        </p>
        <ul>
          <li>Redistribute, resell, or republish audio generated by our apps.</li>
          <li>Attempt to reverse-engineer, modify, or tamper with the apps.</li>
          <li>Use the apps in any way that violates applicable laws or regulations.</li>
        </ul>

        <h2>Accounts</h2>
        <p>
          You may use our apps without creating an account. If you choose to create one (via
          Apple Sign-In, Google, or email), you are responsible for maintaining the security of
          your account credentials. You can delete your account at any time by contacting us.
        </p>

        <h2>Subscriptions &amp; Purchases</h2>
        <p>
          Some features require a paid subscription or one-time purchase (&ldquo;Pro&rdquo;).
          Subscriptions are billed through the Apple App Store or Google Play Store and are
          subject to their respective terms.
        </p>
        <ul>
          <li>Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current billing period.</li>
          <li>You can manage or cancel your subscription in your device&apos;s account settings.</li>
          <li>Refunds are handled by Apple or Google according to their refund policies.</li>
          <li>Lifetime purchases grant permanent access to Pro features and do not renew.</li>
        </ul>

        <h2>Free Tier &amp; Advertising</h2>
        <p>
          Free-tier users have access to all content with periodic ads between chapters. Ads are
          served by Google AdMob and are filtered for age-appropriate content. Upgrading to Pro
          removes all ads.
        </p>

        <h2>Content</h2>
        <p>
          HearVerse provides Bible text (KJV, ASV) in the public domain. HearZ provides
          summaries of publicly available news articles. We do not claim ownership of the
          underlying source content. AI-generated audio is provided for personal listening only.
        </p>

        <h2>Availability &amp; Changes</h2>
        <p>
          We strive to keep our apps available and reliable, but we do not guarantee
          uninterrupted access. We may update, modify, or discontinue features at any time.
          Significant changes to these Terms will be communicated through the app or this page.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          Our apps are provided &ldquo;as is&rdquo; without warranties of any kind. To the
          fullest extent permitted by law, SkoobiLabs shall not be liable for any indirect,
          incidental, or consequential damages arising from your use of our apps.
        </p>

        <h2>Governing Law</h2>
        <p>
          These Terms are governed by the laws of the State of California, United States,
          without regard to conflict of law provisions.
        </p>

        <h2>Contact Us</h2>
        <p>
          If you have questions about these Terms, contact us at{" "}
          <a href="mailto:ask@skoobilabs.com">ask@skoobilabs.com</a>.
        </p>

        <a href="/" className="back">&larr; Back to Skoobi Labs</a>
      </div>
    </>
  );
}
